version: "3.9"

services: 
    api:
        # configuration options that are applied at build time
        build: 
            # a path to a directory containing a Dockerfile
            context: .
        # express dependency between services
        depends_on: 
            - db
        ports: 
            - 5000:5000
        volumes: 
            - ./:/app
    db:
        image: postgres:12.6-alpine
        ports: 
            - 5432:5432
        volumes: 
            - pgdata:/var/lib/postgresql/data
        environment: 
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}

volumes: 
    pgdata:
